### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by impleri** [RobinMalfait/EventSourcing#1]
Hi, is there any documentation in implementing this? Or source code of an example app (todo or otherwise)? Thanks!

**Comment by RobinMalfait** [comment]
No there is no documentation, are you interested in using this package @impleri ?

Because I mainly made it to use for my own projects, but if people want to use it, I'll start with optimizing it, when necessary :)

**Comment by impleri** [comment]
I am certainly interested in using this package. It looks lightweight and builds off of Laravel's existing structures. I've believe that the main implementation is using the generator commands, but knowing how it interacts with Eloquent models (if at all) and the controllers would be very useful.

**Comment by RobinMalfait** [comment]
@impleri currently I don't have any public projects with this package but, I only use Eloquent on my "read" side, you can ask any questions if you want.

From controllers I basically do
1. Validation
2. new Command
3. dispatch command
   1. Checks validation on value objects
   2. Checks invariants
   3. All good? -> Puts generated events in events store
   4. Executes projectors (to store a state) in a db or something
4. done

**Comment by impleri** [comment]
Thanks for the offer. I'm now starting to play around implementing this. I've generated scaffolding (Member) and a related Command (Join). I'm a bit flummoxed of what happens next. I can't find an explicit Command Bus. Am I supposed to use the Event system built into Laravel and provide the Command as the payload?

I think that after transforming a Command into a DomainEvent, the process is to apply the Event to the AggregateRoot, then trigger save on the related Repository. This then triggers applyAnEvent on the AggregateRoot which expected an applyCommand method. I'm not sure what should happen here. Is this where the CommandHandler is triggered?

Lastly, how do you implement multiple Aggregates on the same Entity? For example, Recruit and Moderator are both Members, but I want to separate functionality to match language. Do you scaffold these out separately? And if so, how do you pull other Entities into the Aggregate (do you just use the class constructor DI in Laravel 5)?
